### ISSUE TITLE
Nothing wrong with the code but...

### ISSUE THREAD

**Issue by Lukemul6** [QuentinVezzani/NitroSniper#10]
Just a disclaimer, this got my 2 year old account banned. I ran it over night, got 6 nitros then a couple hours later I got banned and an email from discord saying I was banned for using selfbots.

**Comment by Vedza** [comment]
It looks like It happen when you run multiple self bots at the same time or claim to much Nitro in a short amount of time. I guess I'm on bad servers because I ran it a few hours a days and only got 3 nitro in over a month and never got banned. I will still put a disclaimer. Thank you for sharing your experience.
